# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0
name: OpenSSF Scorecard Analysis
on:
  schedule:
    - cron: "50 1 * * 6"
    - cron: "50 1 * * 3"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  scorecard-analysis:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: diggsweden/reusable-ci/.github/workflows/security-openssf-scorecard.yml@c9d1aa14de12397376162378e5cb218e0750c550 # v2.1.1
    with:
      publish-results: true
